#!/usr/bin/env python3
"""
Build src/data/kgSnapshot.ts from raw KG API JSON responses.

Inputs (paths relative to the MCP tool-result cache):
  V26S: 1776832117153.txt
  V25F: 1776832125428.txt
  ST25F: 1776832127304.txt
  ST26S: 1776832128465.txt
"""
import json
import sys
from pathlib import Path

BASE = Path('C:/Users/AD1305/.claude/projects/D--WORKSPACE-260422-defectReport/97cfa83c-7cb7-42fc-8953-1f561fc8ae43/tool-results')
FILES = {
    'V26S': '1776832117153',
    'V25F': '1776832125428',
    'ST25F': '1776832127304',
    'ST26S': '1776832128465',
}

ESSENTIAL_FIELDS = [
    'PRDT_CD', 'BRD_CD', 'BRD_NM', 'SYS_BRD_NM', 'PRDT_NM',
    'ITEM_NM', 'ITEM_NM_ENG', 'PARENT_PRDT_KIND_NM', 'PRDT_KIND_NM',
    'SESN', 'SESN_SUB_NM', 'SEX_NM', 'ADULT_KIDS_NM',
    'TAG_PRICE', 'PRDT_IMG_URL', 'CAD_PDF_URL', 'STOR_DT_1ST',
]

def load(stamp):
    path = next(BASE.glob(f'*{stamp}.txt'))
    raw = path.read_text(encoding='utf-8')
    # MCP output format: {"success": true, "api_name": ..., "data": {"status": "success", "data": [...]}}
    payload = json.loads(raw)
    items = payload['data']['data']
    return items

def esc(s):
    if s is None: return 'null'
    return "'" + str(s).replace('\\', '\\\\').replace("'", "\\'") + "'"

def to_ts_line(row):
    parts = []
    parts.append(f"PRDT_CD:{esc(row['PRDT_CD'])}")
    parts.append(f"BRD_CD:{esc(row['BRD_CD'])}")
    parts.append(f"BRD_NM:{esc(row['BRD_NM'])}")
    parts.append(f"SYS_BRD_NM:{esc(row['SYS_BRD_NM'])}")
    parts.append(f"PRDT_NM:{esc(row['PRDT_NM'])}")
    parts.append(f"ITEM_NM:{esc(row['ITEM_NM'])}")
    parts.append(f"ITEM_NM_ENG:{esc(row['ITEM_NM_ENG'])}")
    parts.append(f"PARENT_PRDT_KIND_NM:{esc(row['PARENT_PRDT_KIND_NM'])}")
    parts.append(f"PRDT_KIND_NM:{esc(row['PRDT_KIND_NM'])}")
    parts.append(f"SESN:{esc(row['SESN'])}")
    parts.append(f"SESN_SUB_NM:{esc(row['SESN_SUB_NM'])}")
    parts.append(f"SEX_NM:{esc(row['SEX_NM'])}")
    parts.append(f"ADULT_KIDS_NM:{esc(row['ADULT_KIDS_NM'])}")
    price = row.get('TAG_PRICE')
    parts.append(f"TAG_PRICE:{int(price) if price is not None else 0}")
    parts.append(f"PRDT_IMG_URL:{esc(row.get('PRDT_IMG_URL'))}")
    parts.append(f"CAD_PDF_URL:{esc(row.get('CAD_PDF_URL'))}")
    parts.append(f"STOR_DT_1ST:{esc(row.get('STOR_DT_1ST'))}")
    return '  { ' + ', '.join(parts) + ' },'

def main():
    all_rows = []
    section_rows = {}
    for key, stamp in FILES.items():
        rows = load(stamp)
        section_rows[key] = rows
        all_rows.extend(rows)
        print(f'{key}: {len(rows)} styles', file=sys.stderr)

    out = [
        '// F&F Knowledge Graph snapshot — pulled 2026-04-22 via execute_kg_api_to_context.',
        '// Full dump: DUVETICA (V) + SERGIO TACCHINI (ST) × 25FW / 26SS',
        f'// Generated by scripts/build-kg-snapshot.py · total {len(all_rows)} styles',
        '',
        'export type RawKGProduct = {',
        '  PRDT_CD: string;',
        "  BRD_CD: 'V' | 'ST';",
        '  BRD_NM: string;',
        '  SYS_BRD_NM: string;',
        '  PRDT_NM: string;',
        '  ITEM_NM: string;',
        '  ITEM_NM_ENG: string;',
        '  PARENT_PRDT_KIND_NM: string;',
        '  PRDT_KIND_NM: string;',
        "  SESN: '25F' | '26S';",
        '  SESN_SUB_NM: string;',
        '  SEX_NM: string;',
        '  ADULT_KIDS_NM: string;',
        '  TAG_PRICE: number;',
        '  PRDT_IMG_URL: string | null;',
        '  CAD_PDF_URL: string | null;',
        '  STOR_DT_1ST: string | null;',
        '};',
        '',
        'export const RAW_KG: RawKGProduct[] = [',
    ]

    for key in ('V25F', 'V26S', 'ST25F', 'ST26S'):
        rows = section_rows[key]
        label = {
            'V25F': 'DUVETICA 25FW',
            'V26S': 'DUVETICA 26SS',
            'ST25F': 'SERGIO TACCHINI 25FW',
            'ST26S': 'SERGIO TACCHINI 26SS',
        }[key]
        out.append(f'  // ── {label} ({len(rows)}) ──')
        for r in rows:
            out.append(to_ts_line(r))

    out.append('];')
    out.append('')
    out.append('// Real supplier pool per brand (MFAC_COMPY_NM / MFAC_COMPY).')
    out.append("export const SUPPLIER_POOL: Record<'V' | 'ST', Array<[string, string]>> = {")
    out.append('  V: [')
    out.append("    ['(주)신명훠스트', '810191'],")
    out.append("    ['주식회사 세종티에프', '116873'],")
    out.append("    ['(주)아이보리', '810200'],")
    out.append("    ['㈜인티모', '119427'],")
    out.append("    ['주식회사 엠에스에프', '200603'],")
    out.append('  ],')
    out.append('  ST: [')
    out.append("    ['(주) 세기와사람들', '200534'],")
    out.append("    ['트윈텍스타일', '200546'],")
    out.append("    ['(주)신티에스', '123632'],")
    out.append("    ['주식회사 이음에프앤씨', '200539'],")
    out.append("    ['㈜원지아이엔씨', '111160'],")
    out.append('  ],')
    out.append('};')
    out.append('')
    out.append('export const KG_META = {')
    out.append("  fetchedAt: '2026-04-22',")
    out.append("  source: 'F&F Knowledge Graph · execute_kg_api_to_context',")
    out.append("  endpoint: '/api/v1/hq/search/product_codes_properties',")
    out.append('  totalProducts: RAW_KG.length,')
    out.append('};')
    out.append('')

    Path('src/data/kgSnapshot.ts').write_text('\n'.join(out), encoding='utf-8')
    print(f'Wrote {len(all_rows)} styles to src/data/kgSnapshot.ts', file=sys.stderr)

if __name__ == '__main__':
    main()
