#!/usr/bin/env python3
"""Aggregate PO rows → per-PRDT_CD supplier/qty/PO. Emit src/data/poOverrides.ts."""
import json
import sys
from collections import defaultdict
from pathlib import Path

SRC = Path('scripts/po-data-raw.json')
OUT = Path('src/data/poOverrides.ts')


def esc(s: str) -> str:
    if s is None:
        return 'null'
    return "'" + str(s).replace('\\', '\\\\').replace("'", "\\'") + "'"


def main() -> None:
    payload = json.loads(SRC.read_text(encoding='utf-8'))
    rows = payload['rows']

    # Aggregate: primary supplier = first encountered, total qty = sum, primary PO = first
    agg: dict[str, dict] = defaultdict(lambda: {'supplier': None, 'origin': None, 'qty': 0, 'po': None, 'po_count': 0})
    for r in rows:
        k = r['PRDT_CD']
        a = agg[k]
        if a['supplier'] is None:
            a['supplier'] = r['MFAC_COMPY_NM']
            a['origin'] = r['ORIGIN_NM']
            a['po'] = r['PO_NO']
        a['qty'] += int(r['ORD_QTY'])
        a['po_count'] += 1

    lines = [
        '// Auto-generated by scripts/build-po-overrides.py · 2026-04-22',
        '// Real F&F KG PO data per PRDT_CD (aggregated across all POs of that style)',
        '',
        'export type POOverride = {',
        '  supplier: string;',
        '  origin: string;',
        '  receivedQty: number;',
        '  poNumber: string;',
        '  poCount: number;',
        '};',
        '',
        'export const PO_OVERRIDES: Record<string, POOverride> = {',
    ]
    for prdt_cd in sorted(agg.keys()):
        a = agg[prdt_cd]
        lines.append(
            f"  {esc(prdt_cd)}: {{ supplier: {esc(a['supplier'])}, origin: {esc(a['origin'])}, "
            f"receivedQty: {a['qty']}, poNumber: {esc(a['po'])}, poCount: {a['po_count']} }},"
        )
    lines.append('};')
    lines.append('')

    OUT.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Wrote {len(agg)} PRDT_CDs with PO overrides → {OUT}', file=sys.stderr)


if __name__ == '__main__':
    main()
